[Update] set TERM to tmux-256color in Tmux Env
set TERM=tmux-256color correct text effect,
    refer to https://github.com/gpakosz/.tmux/pull/386:
        echo -e "\e[3mitalic\e[0m"

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -30,10 +30,10 @@ function export-add {
 }
 
 function tmux-export {
-    if ! [[ "$TERM" =~ "screen".* ]]; then
-        >&2 echo "error: not in tmux session."
-        return 2
-    fi
+    case "$TERM" in
+        tmux-*|screen-*) ;;
+        *) >&2 echo "error: not in tmux session."; return 2 ;;
+    esac
 
     name=${1%%=*}
     value=${1#*=}
@@ -55,9 +55,10 @@ export LANG=en_US.UTF-8
 export EDITOR=vim
 
 # enfore xterm-256color if not within TMUX
-if [[ "$TERM" != "screen-256color" ]]; then
-    export TERM=xterm-256color
-fi
+case "$TERM" in
+    *-256color) ;;
+    *) export TERM=xterm-256color
+esac
 
 export _PROMPT_VARS=(IP PORT)
 
